/*
 * timer_cfg.h
 *
 * Created: 10/24/2023 12:19:17 AM
 *  Author: sharb
 */ 


#ifndef TIMER_CFG_H_
#define TIMER_CFG_H_


/*
	select timer0 frequency :
	1-TIMER0_FREQUENCY_1M      
	2-TIMER0_FREQUENCY_8M   
	3-TIMER0_FREQUENCY_16M         
    
	
*/
#define TIMER0_SELECT_FREQ      TIMER0_FREQUENCY_8M

/*
	select timer0 mode :
	1-TIMER0_NORMAL_MODE      
	2-TIMER0_PWM_PHASE_MODE   
	3-TIMER0_CTC_MODE         
	4-TIMER0_FAST_PWM_MODE    
	
*/
#define TIMER0_SELECT_MODE      TIMER0_NORMAL_MODE

/*

	select FAST PWM INVERTD :
	1-PWM_INVERTED
	2-PWM_NON_INVERTED    
	
*/
#define FAST_PWM_INVERTED_OPTION   PWM_NON_INVERTED


/*

	select timer0 CLOCK :
	1-TIMER0_NO_PRESCALER
	2-TIMER0_8_PRESCALER
	3-TIMER0_64_PRESCALER
	4-TIMER0_256_PRESCALER
	5-TIMER0_1024_PRESCALER
	
	// USER SHOULD DEFINE THESE TWO MACROS IF EXTERNAL CLOCK IS USED
	6-TIMER0_EXT_CLOCK_FALLING
	7-TIMER0_EXT_CLOCK_RISING    
	
*/
#define TIMER0_SELECT_CLOCK    TIMER0_8_PRESCALER


/*

	select timer0 interrupt status :
	1-TIMER0_INTERRUPT_ENABLE
	2-TIMER0_INTERRUPT_DISABLE
   
	
*/
#define TIMER0_SELECT_INTERRUPT    TIMER0_INTERRUPT_ENABLE

/*

	select FAST PWM INVERTD :
	1-PWM_INVERTED
	2-PWM_NON_INVERTED    
	
*/
#define FAST_PWM_INVERTED        PWM_INVERTED



#endif /* TIMER_CFG_H_ */