#ifndef GPIO_CFG_H
#define GPIO_CFG_H
/*
						
 GPIO_LSP_INPUT_____PU_MODE	 
 GPIO_LSP_INPUT_____PD_MODE   
 GPIO_LSP_OUTPUT_PP_PU_MODE   
 GPIO_LSP_OUTPUT_PP_PU_MODE   
 GPIO_LSP_OUTPUT_OD_PD_MODE	 
 GPIO_LSP_OUTPUT_OD_PD_MODE	 
 GPIO_LSP_ALTERNATE_PP_MODE	 
 GPIO_LSP_ALTERNATE_OD_MODE	 
 GPIO_LSP_ANALOG_______MODE	 

									   
 GPIO_HSP_INPUT_____PU_MODE	 
 GPIO_HSP_INPUT_____PD_MODE   
 GPIO_HSP_OUTPUT_PP_PU_MODE   
 GPIO_HSP_OUTPUT_PP_PU_MODE   
 GPIO_HSP_OUTPUT_OD_PD_MODE	 
 GPIO_HSP_OUTPUT_OD_PD_MODE	 
 GPIO_HSP_ALTERNATE_PP_MODE	 
 GPIO_HSP_ALTERNATE_OD_MODE	 
 GPIO_HSP_ANALOG_______MODE	 

						
 GPIO_MSP_INPUT_____PU_MODE	 
 GPIO_MSP_INPUT_____PD_MODE   
 GPIO_MSP_OUTPUT_PP_PU_MODE   
 GPIO_MSP_OUTPUT_PP_PU_MODE   
 GPIO_MSP_OUTPUT_OD_PD_MODE	 
 GPIO_MSP_OUTPUT_OD_PD_MODE	 
 GPIO_MSP_ALTERNATE_PP_MODE	 
 GPIO_MSP_ALTERNATE_OD_MODE	 
 GPIO_MSP_ANALOG_______MODE	 

						
 GPIO_VHSP_INPUT_____PU_MODE	 
 GPIO_VHSP_INPUT_____PD_MODE   
 GPIO_VHSP_OUTPUT_PP_PU_MODE   
 GPIO_VHSP_OUTPUT_PP_PU_MODE   
 GPIO_VHSP_OUTPUT_OD_PD_MODE	 
 GPIO_VHSP_OUTPUT_OD_PD_MODE	 
 GPIO_VHSP_ALTERNATE_PP_MODE	 
 GPIO_VHSP_ALTERNATE_OD_MODE	 
 GPIO_VHSP_ANALOG_______MODE	 
*/
/*PERIFERAL A*/
#define GPIO_PIN_PA00     GPIO_VHSP_OUTPUT_PP_PU_MODE    								
#define GPIO_PIN_PA01     GPIO_VHSP_OUTPUT_PP_PU_MODE   							
#define GPIO_PIN_PA02     GPIO_VHSP_OUTPUT_PP_PU_MODE    							
#define GPIO_PIN_PA03     GPIO_VHSP_OUTPUT_PP_PU_MODE    							
#define GPIO_PIN_PA04     GPIO_VHSP_OUTPUT_PP_PU_MODE    							
#define GPIO_PIN_PA05     GPIO_VHSP_OUTPUT_PP_PU_MODE    							
#define GPIO_PIN_PA06     GPIO_VHSP_OUTPUT_PP_PU_MODE    							
#define GPIO_PIN_PA07     GPIO_VHSP_OUTPUT_PP_PU_MODE    							
#define GPIO_PIN_PA08     GPIO_VHSP_OUTPUT_PP_PU_MODE    							
#define GPIO_PIN_PA09     GPIO_VHSP_OUTPUT_PP_PU_MODE    							
#define GPIO_PIN_PA10     GPIO_VHSP_OUTPUT_PP_PU_MODE    								
#define GPIO_PIN_PA11     GPIO_VHSP_OUTPUT_PP_PU_MODE    								
#define GPIO_PIN_PA12     GPIO_VHSP_OUTPUT_PP_PU_MODE    								
#define GPIO_PIN_PA13     GPIO_VHSP_OUTPUT_PP_PU_MODE    								
#define GPIO_PIN_PA14     GPIO_VHSP_OUTPUT_PP_PU_MODE    								
#define GPIO_PIN_PA15     GPIO_VHSP_OUTPUT_PP_PU_MODE

/*PERIFERAL B*/
#define GPIO_PIN_PB00       GPIO_VHSP_OUTPUT_PP_PU_MODE  								
#define GPIO_PIN_PB01       GPIO_VHSP_OUTPUT_PP_PU_MODE 							
#define GPIO_PIN_PB02       GPIO_VHSP_OUTPUT_PP_PU_MODE  							
#define GPIO_PIN_PB03       GPIO_VHSP_OUTPUT_PP_PU_MODE  							
#define GPIO_PIN_PB04       GPIO_VHSP_OUTPUT_PP_PU_MODE  							
#define GPIO_PIN_PB05       GPIO_VHSP_OUTPUT_PP_PU_MODE  							
#define GPIO_PIN_PB06       GPIO_VHSP_OUTPUT_PP_PU_MODE  							
#define GPIO_PIN_PB07       GPIO_VHSP_OUTPUT_PP_PU_MODE  							
#define GPIO_PIN_PB08       GPIO_VHSP_OUTPUT_PP_PU_MODE  							
#define GPIO_PIN_PB09       GPIO_VHSP_OUTPUT_PP_PU_MODE  							
#define GPIO_PIN_PB10       GPIO_VHSP_OUTPUT_PP_PU_MODE  								
#define GPIO_PIN_PB11       GPIO_VHSP_OUTPUT_PP_PU_MODE  								
#define GPIO_PIN_PB12       GPIO_VHSP_OUTPUT_PP_PU_MODE  								
#define GPIO_PIN_PB13       GPIO_VHSP_OUTPUT_PP_PU_MODE  								
#define GPIO_PIN_PB14       GPIO_VHSP_OUTPUT_PP_PU_MODE  								
#define GPIO_PIN_PB15       GPIO_VHSP_OUTPUT_PP_PU_MODE

/*PERIFERAL C*/
#define GPIO_PIN_PC00      GPIO_VHSP_OUTPUT_PP_PU_MODE   								
#define GPIO_PIN_PC01      GPIO_VHSP_OUTPUT_PP_PU_MODE  							
#define GPIO_PIN_PC02      GPIO_VHSP_OUTPUT_PP_PU_MODE   							
#define GPIO_PIN_PC03      GPIO_VHSP_OUTPUT_PP_PU_MODE   							
#define GPIO_PIN_PC04      GPIO_VHSP_OUTPUT_PP_PU_MODE   							
#define GPIO_PIN_PC05      GPIO_VHSP_OUTPUT_PP_PU_MODE   							
#define GPIO_PIN_PC06      GPIO_VHSP_OUTPUT_PP_PU_MODE   							
#define GPIO_PIN_PC07      GPIO_VHSP_OUTPUT_PP_PU_MODE   							
#define GPIO_PIN_PC08      GPIO_VHSP_OUTPUT_PP_PU_MODE   							
#define GPIO_PIN_PC09      GPIO_VHSP_OUTPUT_PP_PU_MODE   							
#define GPIO_PIN_PC10      GPIO_VHSP_OUTPUT_PP_PU_MODE   								
#define GPIO_PIN_PC11      GPIO_VHSP_OUTPUT_PP_PU_MODE   								
#define GPIO_PIN_PC12      GPIO_VHSP_OUTPUT_PP_PU_MODE   								
#define GPIO_PIN_PC13      GPIO_VHSP_OUTPUT_PP_PU_MODE   								
#define GPIO_PIN_PC14      GPIO_VHSP_OUTPUT_PP_PU_MODE   								
#define GPIO_PIN_PC15      GPIO_VHSP_OUTPUT_PP_PU_MODE
/*PERIFERAL D*/
#define GPIO_PIN_PD00      GPIO_VHSP_OUTPUT_PP_PU_MODE   								
#define GPIO_PIN_PD01      GPIO_VHSP_OUTPUT_PP_PU_MODE  							
#define GPIO_PIN_PD02      GPIO_VHSP_OUTPUT_PP_PU_MODE   							
#define GPIO_PIN_PD03      GPIO_VHSP_OUTPUT_PP_PU_MODE   							
#define GPIO_PIN_PD04      GPIO_VHSP_OUTPUT_PP_PU_MODE   							
#define GPIO_PIN_PD05      GPIO_VHSP_OUTPUT_PP_PU_MODE   							
#define GPIO_PIN_PD06      GPIO_VHSP_OUTPUT_PP_PU_MODE   							
#define GPIO_PIN_PD07      GPIO_VHSP_OUTPUT_PP_PU_MODE   							
#define GPIO_PIN_PD08      GPIO_VHSP_OUTPUT_PP_PU_MODE   							
#define GPIO_PIN_PD09      GPIO_VHSP_OUTPUT_PP_PU_MODE   							
#define GPIO_PIN_PD10      GPIO_VHSP_OUTPUT_PP_PU_MODE   								
#define GPIO_PIN_PD11      GPIO_VHSP_OUTPUT_PP_PU_MODE   								
#define GPIO_PIN_PD12      GPIO_VHSP_OUTPUT_PP_PU_MODE   								
#define GPIO_PIN_PD13      GPIO_VHSP_OUTPUT_PP_PU_MODE   								
#define GPIO_PIN_PD14      GPIO_VHSP_OUTPUT_PP_PU_MODE   								
#define GPIO_PIN_PD15      GPIO_VHSP_OUTPUT_PP_PU_MODE
/*PERIFERAL E*/
#define GPIO_PIN_PE00     GPIO_VHSP_OUTPUT_PP_PU_MODE    								
#define GPIO_PIN_PE01     GPIO_VHSP_OUTPUT_PP_PU_MODE   							
#define GPIO_PIN_PE02     GPIO_VHSP_OUTPUT_PP_PU_MODE    							
#define GPIO_PIN_PE03     GPIO_VHSP_OUTPUT_PP_PU_MODE    							
#define GPIO_PIN_PE04     GPIO_VHSP_OUTPUT_PP_PU_MODE    							
#define GPIO_PIN_PE05     GPIO_VHSP_OUTPUT_PP_PU_MODE    							
#define GPIO_PIN_PE06     GPIO_VHSP_OUTPUT_PP_PU_MODE    							
#define GPIO_PIN_PE07     GPIO_VHSP_OUTPUT_PP_PU_MODE    							
#define GPIO_PIN_PE08     GPIO_VHSP_OUTPUT_PP_PU_MODE    							
#define GPIO_PIN_PE09     GPIO_VHSP_OUTPUT_PP_PU_MODE    							
#define GPIO_PIN_PE10     GPIO_VHSP_OUTPUT_PP_PU_MODE    								
#define GPIO_PIN_PE11     GPIO_VHSP_OUTPUT_PP_PU_MODE    								
#define GPIO_PIN_PE12     GPIO_VHSP_OUTPUT_PP_PU_MODE    								
#define GPIO_PIN_PE13     GPIO_VHSP_OUTPUT_PP_PU_MODE    								
#define GPIO_PIN_PE14     GPIO_VHSP_OUTPUT_PP_PU_MODE    								
#define GPIO_PIN_PE15     GPIO_VHSP_OUTPUT_PP_PU_MODE
/*PERIFERAL H*/
#define GPIO_PIN_PH00     GPIO_VHSP_OUTPUT_PP_PU_MODE    								
#define GPIO_PIN_PH01     GPIO_VHSP_OUTPUT_PP_PU_MODE   							
#define GPIO_PIN_PH02     GPIO_VHSP_OUTPUT_PP_PU_MODE    							
#define GPIO_PIN_PH03     GPIO_VHSP_OUTPUT_PP_PU_MODE    							
#define GPIO_PIN_PH04     GPIO_VHSP_OUTPUT_PP_PU_MODE    							
#define GPIO_PIN_PH05     GPIO_VHSP_OUTPUT_PP_PU_MODE    							
#define GPIO_PIN_PH06     GPIO_VHSP_OUTPUT_PP_PU_MODE    							
#define GPIO_PIN_PH07     GPIO_VHSP_OUTPUT_PP_PU_MODE    							
#define GPIO_PIN_PH08     GPIO_VHSP_OUTPUT_PP_PU_MODE    							
#define GPIO_PIN_PH09     GPIO_VHSP_OUTPUT_PP_PU_MODE    							
#define GPIO_PIN_PH10     GPIO_VHSP_OUTPUT_PP_PU_MODE    								
#define GPIO_PIN_PH11     GPIO_VHSP_OUTPUT_PP_PU_MODE    								
#define GPIO_PIN_PH12     GPIO_VHSP_OUTPUT_PP_PU_MODE    								
#define GPIO_PIN_PH13     GPIO_VHSP_OUTPUT_PP_PU_MODE    								
#define GPIO_PIN_PH14     GPIO_VHSP_OUTPUT_PP_PU_MODE    								
#define GPIO_PIN_PH15     GPIO_VHSP_OUTPUT_PP_PU_MODE

#endif