/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


#include <Services/Memory_Map.h>
#include <MCAL/RCC/RCC_Includes/RCC.h>
#include <MCAL/GPIO/GPIO_Includes/Gpio.h>

void GPIO_Debug(void);

int main()
{
	GPIO_Debug();
	return 0;
}

void GPIO_Debug(void)
{
	GPIO_Init_Static2(GPIO_PORT_C);
	GPIO_Init_Static2(GPIO_PORT_E);
	GpioPinCfg_t CnfgStruct = {GPIO_MODE_OUTPUT_PP, GPIO_PUPD_u32_PULL_DOWN, GPIO_SPEED_HIGH, GPIO_PIN_05, GPIO_PORT_E};
	Gpio_init(&CnfgStruct);
	Gpio_setPinValue1(&CnfgStruct, GPIO_PIN_HIGH);
	Gpio_setPinValue2(GPIO_PORT_E, GPIO_PIN_05, GPIO_PIN_LOW);
	CnfgStruct.gpio_mode_x = GPIO_MODE_AF;
	CnfgStruct.gpio_pin_x = GPIO_PIN_11;
	Gpio_init(&CnfgStruct);
	Gpio_SetAlternateFunction(&CnfgStruct, GPIO_AF_13);
	Rcc_enuEnablePeriphral(RCC_REGISTER_AHB1, AHB1_GPIOA_EN);
}

