/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


#include <Services/Memory_Map.h>
#include <MCAL/RCC/RCC_Includes/RCC.h>
#include <MCAL/GPIO/GPIO_Includes/Gpio.h>
void RCC_Debug(void);
int main()
{
	RCC_Debug();
	return 0;
}

void RCC_Debug(void)
{
	Rcc_enuCnfgrPll(2,3,RCC_PLLP_DIVBY_2, RCC_PLLSRC_HSE, RCC_Q_DIVBY_2 );
	Rcc_enuControlCLk(RCC_CNTROL_HSION, RCC_CNTROL_HSEON, RCC_CNTROL_PLLMainON, RCC_CNTROL_PLLI2SON);
	Rcc_enuSelectSysCLk(RCC_CLK_HSE, RCC_STATE_PRESERVE);
	Rcc_enuEnablePeriphral(RCC_REGISTER_AHB1, AHB1_GPIOA_EN);
	Rcc_enuDisablePeriphral(RCC_REGISTER_AHB1, AHB1_GPIOA_EN);
	Rcc_enuCfgBusPrescalers(RCC_REGISTER_APB2, RCC_APB2_DIV4);
}
