/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


#include <Services/Memory_Map.h>
#include <MCAL/RCC/RCC_Includes/RCC.h>
#include <MCAL/GPIO/GPIO_Includes/Gpio.h>
#include <MCAL/SYS_TIC/SYS_TIC_Includes/SYSTIC.h>
void SysTic_Debug(void);

int main()
{

	SysTic_Debug();
	return 0;
}


void SysTic_Debug(void)
{
	SysTic_CFG_t SysTic_CFG = {SYSTICK_PRESCALER_DIV1, TICKINT_State_Disable, PTR_NULL};
	Systick_Init(&SysTic_CFG);
	Systick_Start(1000000);
	Systick_Stop();
}
