#ifndef PORT_CFG_H_
#define PORT_CFG_H_
/*PORTA PINS  initial MODE*/
#define DIO_u8MODEPORTAPIN0			PORT_u8PINMODE_OUTPUT_LOW
#define DIO_u8MODEPORTAPIN1			PORT_u8PINMODE_OUTPUT_LOW
#define DIO_u8MODEPORTAPIN2			PORT_u8PINMODE_OUTPUT_LOW
#define DIO_u8MODEPORTAPIN3			PORT_u8PINMODE_OUTPUT_LOW
#define DIO_u8MODEPORTAPIN4			PORT_u8PINMODE_OUTPUT_LOW
#define DIO_u8MODEPORTAPIN5			PORT_u8PINMODE_OUTPUT_LOW
#define DIO_u8MODEPORTAPIN6			PORT_u8PINMODE_OUTPUT_LOW
#define DIO_u8MODEPORTAPIN7			PORT_u8PINMODE_OUTPUT_LOW
/*PORTB PINS  initial MODE*/
#define DIO_u8MODEPORTBPIN0			PORT_u8PINMODE_OUTPUT_LOW
#define DIO_u8MODEPORTBPIN1			PORT_u8PINMODE_OUTPUT_LOW
#define DIO_u8MODEPORTBPIN2			PORT_u8PINMODE_OUTPUT_LOW
#define DIO_u8MODEPORTBPIN3			PORT_u8PINMODE_OUTPUT_LOW
#define DIO_u8MODEPORTBPIN4			PORT_u8PINMODE_OUTPUT_LOW
#define DIO_u8MODEPORTBPIN5			PORT_u8PINMODE_OUTPUT_LOW
#define DIO_u8MODEPORTBPIN6			PORT_u8PINMODE_OUTPUT_LOW
#define DIO_u8MODEPORTBPIN7			PORT_u8PINMODE_OUTPUT_LOW
/*PORTC PINS  initial MODE*/
#define DIO_u8MODEPORTCPIN0			PORT_u8PINMODE_OUTPUT_LOW
#define DIO_u8MODEPORTCPIN1			PORT_u8PINMODE_OUTPUT_LOW
#define DIO_u8MODEPORTCPIN2			PORT_u8PINMODE_OUTPUT_LOW
#define DIO_u8MODEPORTCPIN3			PORT_u8PINMODE_OUTPUT_LOW
#define DIO_u8MODEPORTCPIN4			PORT_u8PINMODE_OUTPUT_LOW
#define DIO_u8MODEPORTCPIN5			PORT_u8PINMODE_OUTPUT_LOW
#define DIO_u8MODEPORTCPIN6			PORT_u8PINMODE_OUTPUT_LOW
#define DIO_u8MODEPORTCPIN7			PORT_u8PINMODE_OUTPUT_LOW
/*PORTD PINS  initial MODE*/
#define DIO_u8MODEPORTDPIN0			PORT_u8PINMODE_OUTPUT_LOW
#define DIO_u8MODEPORTDPIN1			PORT_u8PINMODE_OUTPUT_LOW
#define DIO_u8MODEPORTDPIN2			PORT_u8PINMODE_OUTPUT_LOW
#define DIO_u8MODEPORTDPIN3			PORT_u8PINMODE_OUTPUT_LOW
#define DIO_u8MODEPORTDPIN4			PORT_u8PINMODE_OUTPUT_LOW
#define DIO_u8MODEPORTDPIN5			PORT_u8PINMODE_OUTPUT_LOW
#define DIO_u8MODEPORTDPIN6			PORT_u8PINMODE_OUTPUT_LOW
#define DIO_u8MODEPORTDPIN7			PORT_u8PINMODE_OUTPUT_LOW



#endif

