

#ifndef PORT_CFG_H_
#define PORT_CFG_H_
/************************************************** PORT_u8MODEPINS OPTIONS:-
 	PORT_u8OUTPUT_LOW
 
 
 
	PORT_u8OUTPUT_HIGH
	
	
	
	
	PORT_u8INPUT_FLOATING
	
	
	
	
	
	
	PORT_u8INPUT_PULLUP
	
	

*/


#define PORT_u8u8PORTA_MODEPIN00            PORT_u8INPUT_FLOATING
#define PORT_u8PORTA_MODEPIN01            PORT_u8OUTPUT_LOW
#define PORT_u8u8PORTA_MODEPIN02            PORT_u8OUTPUT_LOW
#define PORT_u8u8PORTA_MODEPIN03            PORT_u8OUTPUT_LOW
#define PORT_u8u8PORTA_MODEPIN04            PORT_u8OUTPUT_LOW
#define PORT_u8u8PORTA_MODEPIN05            PORT_u8OUTPUT_LOW
#define PORT_u8u8PORTA_MODEPIN06            PORT_u8OUTPUT_LOW
#define PORT_u8u8PORTA_MODEPIN07            PORT_u8OUTPUT_LOW

#define PORT_u8PORTB_MODEPIN08            PORT_u8OUTPUT_LOW
#define PORT_u8PORTB_MODEPIN09            PORT_u8OUTPUT_LOW
#define PORT_u8PORTB_MODEPIN10            PORT_u8OUTPUT_LOW
#define PORT_u8PORTB_MODEPIN11            PORT_u8OUTPUT_LOW
#define PORT_u8PORTB_MODEPIN12            PORT_u8OUTPUT_LOW
#define PORT_u8PORTB_MODEPIN13            PORT_u8OUTPUT_LOW
#define PORT_u8PORTB_MODEPIN14            PORT_u8OUTPUT_LOW
#define PORT_u8PORTB_MODEPIN15            PORT_u8OUTPUT_LOW

#define PORT_u8PORTC_MODEPIN16            PORT_u8OUTPUT_LOW
#define PORT_u8PORTC_MODEPIN17            PORT_u8OUTPUT_LOW
#define PORT_u8PORTC_MODEPIN18            PORT_u8OUTPUT_LOW
#define PORT_u8PORTC_MODEPIN19            PORT_u8OUTPUT_LOW
#define PORT_u8PORTC_MODEPIN20            PORT_u8OUTPUT_LOW
#define PORT_u8PORTC_MODEPIN21            PORT_u8OUTPUT_LOW
#define PORT_u8PORTC_MODEPIN22            PORT_u8OUTPUT_LOW
#define PORT_u8PORTC_MODEPIN23            PORT_u8OUTPUT_LOW

#define PORT_u8PORTC_MODEPIN24            PORT_u8INPUT_PULLUP
#define PORT_u8PORTC_MODEPIN25            PORT_u8INPUT_PULLUP
#define PORT_u8PORTC_MODEPIN26            PORT_u8INPUT_PULLUP
#define PORT_u8PORTC_MODEPIN27            PORT_u8INPUT_PULLUP
#define PORT_u8PORTC_MODEPIN28            PORT_u8OUTPUT_HIGH
#define PORT_u8PORTC_MODEPIN29            PORT_u8OUTPUT_HIGH
#define PORT_u8PORTC_MODEPIN30            PORT_u8OUTPUT_HIGH
#define PORT_u8PORTC_MODEPIN31            PORT_u8OUTPUT_HIGH





















#endif /* MCAL_PORT_DRIVER_PORT_CFG_H_ */
