#include "Std_types.h"
#include "Bit_utils.h"

#include "GPIO.h"
#include "GPIO_prv.h"
#include "GPIO_cfg.h"


void PORT_voidInit(void)
{
	u8 GPIOA_u8CfgPins[6][16][4] =
{
	{
		{GPIOA_PIN0_MODER,GPIOA_PIN0_OTYPER,GPIOA_PIN0_OSPEEDR,GPIOA_PIN0_PUPDR},
		{GPIOA_PIN1_MODER,GPIOA_PIN1_OTYPER,GPIOA_PIN1_OSPEEDR,GPIOA_PIN1_PUPDR},
		{GPIOA_PIN2_MODER,GPIOA_PIN2_OTYPER,GPIOA_PIN2_OSPEEDR,GPIOA_PIN2_PUPDR},
		{GPIOA_PIN3_MODER,GPIOA_PIN3_OTYPER,GPIOA_PIN3_OSPEEDR,GPIOA_PIN3_PUPDR},
		{GPIOA_PIN4_MODER,GPIOA_PIN4_OTYPER,GPIOA_PIN4_OSPEEDR,GPIOA_PIN4_PUPDR},
		{GPIOA_PIN5_MODER,GPIOA_PIN5_OTYPER,GPIOA_PIN5_OSPEEDR,GPIOA_PIN5_PUPDR},
		{GPIOA_PIN6_MODER,GPIOA_PIN6_OTYPER,GPIOA_PIN6_OSPEEDR,GPIOA_PIN6_PUPDR},
		{GPIOA_PIN7_MODER,GPIOA_PIN7_OTYPER,GPIOA_PIN7_OSPEEDR,GPIOA_PIN7_PUPDR},
		{GPIOA_PIN8_MODER,GPIOA_PIN8_OTYPER,GPIOA_PIN8_OSPEEDR,GPIOA_PIN8_PUPDR},
		{GPIOA_PIN9_MODER,GPIOA_PIN9_OTYPER,GPIOA_PIN9_OSPEEDR,GPIOA_PIN9_PUPDR},
		{GPIOA_PIN10_MODER,GPIOA_PIN10_OTYPER,GPIOA_PIN10_OSPEEDR,GPIOA_PIN10_PUPDR},
		{GPIOA_PIN11_MODER,GPIOA_PIN11_OTYPER,GPIOA_PIN11_OSPEEDR,GPIOA_PIN11_PUPDR},
		{GPIOA_PIN12_MODER,GPIOA_PIN12_OTYPER,GPIOA_PIN12_OSPEEDR,GPIOA_PIN12_PUPDR},
		{GPIOA_PIN13_MODER,GPIOA_PIN13_OTYPER,GPIOA_PIN13_OSPEEDR,GPIOA_PIN13_PUPDR},
		{GPIOA_PIN14_MODER,GPIOA_PIN14_OTYPER,GPIOA_PIN14_OSPEEDR,GPIOA_PIN14_PUPDR},
		{GPIOA_PIN15_MODER,GPIOA_PIN15_OTYPER,GPIOA_PIN15_OSPEEDR,GPIOA_PIN15_PUPDR}
	},
	{
		{GPIOB_PIN0_MODER,GPIOB_PIN0_OTYPER,GPIOB_PIN0_OSPEEDR,GPIOB_PIN0_PUPDR},
		{GPIOB_PIN1_MODER,GPIOB_PIN1_OTYPER,GPIOB_PIN1_OSPEEDR,GPIOB_PIN1_PUPDR},
		{GPIOB_PIN2_MODER,GPIOB_PIN2_OTYPER,GPIOB_PIN2_OSPEEDR,GPIOB_PIN2_PUPDR},
		{GPIOB_PIN3_MODER,GPIOB_PIN3_OTYPER,GPIOB_PIN3_OSPEEDR,GPIOB_PIN3_PUPDR},
		{GPIOB_PIN4_MODER,GPIOB_PIN4_OTYPER,GPIOB_PIN4_OSPEEDR,GPIOB_PIN4_PUPDR},
		{GPIOB_PIN5_MODER,GPIOB_PIN5_OTYPER,GPIOB_PIN5_OSPEEDR,GPIOB_PIN5_PUPDR},
		{GPIOB_PIN6_MODER,GPIOB_PIN6_OTYPER,GPIOB_PIN6_OSPEEDR,GPIOB_PIN6_PUPDR},
		{GPIOB_PIN7_MODER,GPIOB_PIN7_OTYPER,GPIOB_PIN7_OSPEEDR,GPIOB_PIN7_PUPDR},
		{GPIOB_PIN8_MODER,GPIOB_PIN8_OTYPER,GPIOB_PIN8_OSPEEDR,GPIOB_PIN8_PUPDR},
		{GPIOB_PIN9_MODER,GPIOB_PIN9_OTYPER,GPIOB_PIN9_OSPEEDR,GPIOB_PIN9_PUPDR},
		{GPIOB_PIN10_MODER,GPIOB_PIN10_OTYPER,GPIOB_PIN10_OSPEEDR,GPIOB_PIN10_PUPDR},
		{GPIOB_PIN11_MODER,GPIOB_PIN11_OTYPER,GPIOB_PIN11_OSPEEDR,GPIOB_PIN11_PUPDR},
		{GPIOB_PIN12_MODER,GPIOB_PIN12_OTYPER,GPIOB_PIN12_OSPEEDR,GPIOB_PIN12_PUPDR},
		{GPIOB_PIN13_MODER,GPIOB_PIN13_OTYPER,GPIOB_PIN13_OSPEEDR,GPIOB_PIN13_PUPDR},
		{GPIOB_PIN14_MODER,GPIOB_PIN14_OTYPER,GPIOB_PIN14_OSPEEDR,GPIOB_PIN14_PUPDR},
		{GPIOB_PIN15_MODER,GPIOB_PIN15_OTYPER,GPIOB_PIN15_OSPEEDR,GPIOB_PIN15_PUPDR}
	},
	{
		{GPIOC_PIN0_MODER,GPIOC_PIN0_OTYPER,GPIOC_PIN0_OSPEEDR,GPIOC_PIN0_PUPDR},
		{GPIOC_PIN1_MODER,GPIOC_PIN1_OTYPER,GPIOC_PIN1_OSPEEDR,GPIOC_PIN1_PUPDR},
		{GPIOC_PIN2_MODER,GPIOC_PIN2_OTYPER,GPIOC_PIN2_OSPEEDR,GPIOC_PIN2_PUPDR},
		{GPIOC_PIN3_MODER,GPIOC_PIN3_OTYPER,GPIOC_PIN3_OSPEEDR,GPIOC_PIN3_PUPDR},
		{GPIOC_PIN4_MODER,GPIOC_PIN4_OTYPER,GPIOC_PIN4_OSPEEDR,GPIOC_PIN4_PUPDR},
		{GPIOC_PIN5_MODER,GPIOC_PIN5_OTYPER,GPIOC_PIN5_OSPEEDR,GPIOC_PIN5_PUPDR},
		{GPIOC_PIN6_MODER,GPIOC_PIN6_OTYPER,GPIOC_PIN6_OSPEEDR,GPIOC_PIN6_PUPDR},
		{GPIOC_PIN7_MODER,GPIOC_PIN7_OTYPER,GPIOC_PIN7_OSPEEDR,GPIOC_PIN7_PUPDR},
		{GPIOC_PIN8_MODER,GPIOC_PIN8_OTYPER,GPIOC_PIN8_OSPEEDR,GPIOC_PIN8_PUPDR},
		{GPIOC_PIN9_MODER,GPIOC_PIN9_OTYPER,GPIOA_PIN9_OSPEEDR,GPIOC_PIN9_PUPDR},
		{GPIOC_PIN10_MODER,GPIOC_PIN10_OTYPER,GPIOC_PIN10_OSPEEDR,GPIOC_PIN10_PUPDR},
		{GPIOC_PIN11_MODER,GPIOC_PIN11_OTYPER,GPIOC_PIN11_OSPEEDR,GPIOC_PIN11_PUPDR},
		{GPIOC_PIN12_MODER,GPIOC_PIN12_OTYPER,GPIOC_PIN12_OSPEEDR,GPIOC_PIN12_PUPDR},
		{GPIOC_PIN13_MODER,GPIOC_PIN13_OTYPER,GPIOC_PIN13_OSPEEDR,GPIOC_PIN13_PUPDR},
		{GPIOC_PIN14_MODER,GPIOC_PIN14_OTYPER,GPIOC_PIN14_OSPEEDR,GPIOC_PIN14_PUPDR},
		{GPIOC_PIN15_MODER,GPIOC_PIN15_OTYPER,GPIOC_PIN15_OSPEEDR,GPIOC_PIN15_PUPDR}
	},
	{
		{GPIOD_PIN0_MODER, GPIOD_PIN0_OTYPER, GPIOD_PIN0_OSPEEDR, GPIOD_PIN0_PUPDR},
		{GPIOD_PIN1_MODER, GPIOD_PIN1_OTYPER, GPIOD_PIN1_OSPEEDR, GPIOD_PIN1_PUPDR},
		{GPIOD_PIN2_MODER, GPIOD_PIN2_OTYPER, GPIOD_PIN2_OSPEEDR, GPIOD_PIN2_PUPDR},
		{GPIOD_PIN3_MODER, GPIOD_PIN3_OTYPER, GPIOD_PIN3_OSPEEDR, GPIOD_PIN3_PUPDR},
		{GPIOD_PIN4_MODER, GPIOD_PIN4_OTYPER, GPIOD_PIN4_OSPEEDR, GPIOD_PIN4_PUPDR},
		{GPIOD_PIN5_MODER, GPIOD_PIN5_OTYPER, GPIOD_PIN5_OSPEEDR, GPIOD_PIN5_PUPDR},
		{GPIOD_PIN6_MODER, GPIOD_PIN6_OTYPER, GPIOD_PIN6_OSPEEDR, GPIOD_PIN6_PUPDR},
		{GPIOD_PIN7_MODER, GPIOD_PIN7_OTYPER, GPIOD_PIN7_OSPEEDR, GPIOD_PIN7_PUPDR},
		{GPIOD_PIN8_MODER, GPIOD_PIN8_OTYPER, GPIOD_PIN8_OSPEEDR, GPIOD_PIN8_PUPDR},
		{GPIOD_PIN9_MODER, GPIOD_PIN9_OTYPER, GPIOD_PIN9_OSPEEDR, GPIOD_PIN9_PUPDR},
		{GPIOD_PIN10_MODER,GPIOD_PIN10_OTYPER,GPIOD_PIN10_OSPEEDR,GPIOD_PIN10_PUPDR},
		{GPIOD_PIN11_MODER,GPIOD_PIN11_OTYPER,GPIOD_PIN11_OSPEEDR,GPIOD_PIN11_PUPDR},
		{GPIOD_PIN12_MODER,GPIOD_PIN12_OTYPER,GPIOD_PIN12_OSPEEDR,GPIOD_PIN12_PUPDR},
		{GPIOD_PIN13_MODER,GPIOD_PIN13_OTYPER,GPIOD_PIN13_OSPEEDR,GPIOD_PIN13_PUPDR},
		{GPIOD_PIN14_MODER,GPIOD_PIN14_OTYPER,GPIOD_PIN14_OSPEEDR,GPIOD_PIN14_PUPDR},
		{GPIOD_PIN15_MODER,GPIOD_PIN15_OTYPER,GPIOD_PIN15_OSPEEDR,GPIOD_PIN15_PUPDR}
	},
	{
		{GPIOH_PIN0_MODER, GPIOH_PIN0_OTYPER, GPIOH_PIN0_OSPEEDR, GPIOH_PIN0_PUPDR},
		{GPIOH_PIN1_MODER, GPIOH_PIN1_OTYPER, GPIOH_PIN1_OSPEEDR, GPIOH_PIN1_PUPDR},
		{GPIOH_PIN2_MODER, GPIOH_PIN2_OTYPER, GPIOH_PIN2_OSPEEDR, GPIOH_PIN2_PUPDR},
		{GPIOH_PIN3_MODER, GPIOH_PIN3_OTYPER, GPIOH_PIN3_OSPEEDR, GPIOH_PIN3_PUPDR},
		{GPIOH_PIN4_MODER, GPIOH_PIN4_OTYPER, GPIOH_PIN4_OSPEEDR, GPIOH_PIN4_PUPDR},
		{GPIOH_PIN5_MODER, GPIOH_PIN5_OTYPER, GPIOH_PIN5_OSPEEDR, GPIOH_PIN5_PUPDR},
		{GPIOH_PIN6_MODER, GPIOH_PIN6_OTYPER, GPIOH_PIN6_OSPEEDR, GPIOH_PIN6_PUPDR},
		{GPIOH_PIN7_MODER, GPIOH_PIN7_OTYPER, GPIOH_PIN7_OSPEEDR, GPIOH_PIN7_PUPDR},
		{GPIOH_PIN8_MODER, GPIOH_PIN8_OTYPER, GPIOH_PIN8_OSPEEDR, GPIOH_PIN8_PUPDR},
		{GPIOH_PIN9_MODER, GPIOH_PIN9_OTYPER, GPIOH_PIN9_OSPEEDR, GPIOH_PIN9_PUPDR},
		{GPIOH_PIN10_MODER,GPIOH_PIN10_OTYPER,GPIOH_PIN10_OSPEEDR,GPIOH_PIN10_PUPDR},
		{GPIOH_PIN11_MODER,GPIOH_PIN11_OTYPER,GPIOH_PIN11_OSPEEDR,GPIOH_PIN11_PUPDR},
		{GPIOH_PIN12_MODER,GPIOH_PIN12_OTYPER,GPIOH_PIN12_OSPEEDR,GPIOH_PIN12_PUPDR},
		{GPIOH_PIN13_MODER,GPIOH_PIN13_OTYPER,GPIOH_PIN13_OSPEEDR,GPIOH_PIN13_PUPDR},
		{GPIOH_PIN14_MODER,GPIOH_PIN14_OTYPER,GPIOH_PIN14_OSPEEDR,GPIOH_PIN14_PUPDR},
		{GPIOH_PIN15_MODER,GPIOH_PIN15_OTYPER,GPIOH_PIN15_OSPEEDR,GPIOH_PIN15_PUPDR}
	},
};
	u8 Local_u8CfgLoopCounter;
	u8 Local_u8PeriphLoopCounter;
	
	u32 Local_u32MoSpPuMask = 3;
	u32 Local_u32MoSpPuShift = 0;
	u32 Local_u32OTYPERMask  = 1;
	u32 Local_u32OTYPERShift = 0;
	for(Local_u8PeriphLoopCounter = 0;Local_u8PeriphLoopCounter<6;Local_u8PeriphLoopCounter++)
	{
		for(Local_u8CfgLoopCounter = 0;Local_u8CfgLoopCounter<16;Local_u8CfgLoopCounter++)
		{
		  GPIO[Local_u8PeriphLoopCounter]->MODER   = ((GPIO[Local_u8PeriphLoopCounter]->MODER   & ~(Local_u32MoSpPuMask))|((u32)GPIOA_u8CfgPins[Local_u8PeriphLoopCounter][Local_u8CfgLoopCounter][0]<<Local_u32MoSpPuShift));
		  GPIO[Local_u8PeriphLoopCounter]->OTYPER  = ((GPIO[Local_u8PeriphLoopCounter]->OTYPER   & ~(Local_u32OTYPERMask))|(u32)(GPIOA_u8CfgPins[Local_u8PeriphLoopCounter][Local_u8CfgLoopCounter][1]<<Local_u32OTYPERShift));
		  GPIO[Local_u8PeriphLoopCounter]->OSPEEDR = ((GPIO[Local_u8PeriphLoopCounter]->OSPEEDR & ~(Local_u32MoSpPuMask))|(u32)(GPIOA_u8CfgPins[Local_u8PeriphLoopCounter][Local_u8CfgLoopCounter][2]<<Local_u32MoSpPuShift));
		  GPIO[Local_u8PeriphLoopCounter]->PUPDR   = ((GPIO[Local_u8PeriphLoopCounter]->PUPDR   & ~(Local_u32MoSpPuMask))|(u32)(GPIOA_u8CfgPins[Local_u8PeriphLoopCounter][Local_u8CfgLoopCounter][3]<<Local_u32MoSpPuShift));
			Local_u32MoSpPuMask = (Local_u32MoSpPuMask << 2);
			Local_u32MoSpPuShift+=2;
			Local_u32OTYPERMask = (Local_u32OTYPERMask << 1);
			Local_u32OTYPERShift++; 
		}
		Local_u32MoSpPuMask = 3;
		Local_u32MoSpPuShift = 0;
		Local_u32OTYPERMask  = 1;
		Local_u32OTYPERShift = 0;
	}
}
void Write_GPIOPIN(u8 PORT,u8 PIN ,u8 Signal)
{
	BITBAND_REG(GPIO[PORT]->ODR,PIN) = Signal;
}
u8 GPIO_u16ReadPinVal(u8 PORT,u8 PIN)
{
	u8 ReadVal = GET_BIT(GPIO[PORT]->IDR,PIN);
	return ReadVal;
}
