/*
 * USART_cfg.h
 *
 *  Created on: Oct 28, 2023
 *      Author: Ismail
 */

#ifndef MCAL_USART_USART_CFG_H_
#define MCAL_USART_USART_CFG_H_

/*OPTIONS FOR OPERATING MODE
 *
 * 1-USART_SYNCHRONOUS_MODE
 * 2-USART_ASYNCHRONOUS_MODE
 * */
#define USART_OPERATING_MODE USART_ASYNCHRONOUS_MODE
/*options for parity bit check
 *
 * USART_PARITY_DISABLED
 * USART_PARITY_ODD
 * USART_PARITY_EVEN
 */
#define USART_PARITY_MODE USART_PARITY_EVEN
/*OPTIONS FOR STOP BITS
 * USART_ONE_STOP_BIT
 * USART_TWO_STOP_BIT
 */
#define USART_STOP_MODE USART_ONE_STOP_BIT
/*OPTIONS FOR DATA_BITS
 * USART_FIVE_DATA_BITS
 * USART_SIX_DATA_BITS
 * USART_SEVEN_DATA_BITS
 * USART_EIGHT_DATA_BITS
 * USART_NINE_DATA_BITS
 */
#define USART_DATA_SIZE USART_EIGHT_DATA_BITS
/*OPTIONS FOR BAUD RATE
 * USART_2400
 * USART_4800
 * USART_9600
 * USART_19200
 * USART_38400
 */
#define USART_BAUD_RATE  USART_9600


#endif /* MCAL_USART_USART_CFG_H_ */
