/*
 * GPIO_Private.h
 *
 *  Created on: Nov 6, 2023
 *      Author: computer store
 */

#ifndef GPIO_GPIO_INCLUDES_GPIO_CFG_H_
#define GPIO_GPIO_INCLUDES_GPIO_CFG_H_

#include <MCAL/GPIO/GPIO_Includes/Gpio.h>


//method 2

//ex: #define PORTx_PINx_CFG 	{GPIO_MODE_OUTPUT_OD, GPIO_PUPD_u32_PULL_DOWN, GPIO_SPEED_VHIGH, GPIO_PIN_00, GPIO_PORT_A}

//GPIOA
GpioPinCfg_t GPIOA_PINx_CFG[16] = {
									 {GPIO_MODE_OUTPUT_OD, GPIO_PUPD_u32_PULL_DOWN, GPIO_SPEED_VHIGH, GPIO_PIN_00, GPIO_PORT_A},
									 {GPIO_MODE_OUTPUT_OD, GPIO_PUPD_u32_PULL_DOWN, GPIO_SPEED_VHIGH, GPIO_PIN_01, GPIO_PORT_A},
									 {GPIO_MODE_OUTPUT_OD, GPIO_PUPD_u32_PULL_DOWN, GPIO_SPEED_VHIGH, GPIO_PIN_02, GPIO_PORT_A},
									 {GPIO_MODE_OUTPUT_OD, GPIO_PUPD_u32_PULL_DOWN, GPIO_SPEED_VHIGH, GPIO_PIN_03, GPIO_PORT_A},
									 {GPIO_MODE_OUTPUT_OD, GPIO_PUPD_u32_PULL_DOWN, GPIO_SPEED_VHIGH, GPIO_PIN_04, GPIO_PORT_A},
									 {GPIO_MODE_OUTPUT_OD, GPIO_PUPD_u32_PULL_DOWN, GPIO_SPEED_VHIGH, GPIO_PIN_05, GPIO_PORT_A},
									 {GPIO_MODE_OUTPUT_OD, GPIO_PUPD_u32_PULL_DOWN, GPIO_SPEED_VHIGH, GPIO_PIN_06, GPIO_PORT_A},
									 {GPIO_MODE_OUTPUT_OD, GPIO_PUPD_u32_PULL_DOWN, GPIO_SPEED_VHIGH, GPIO_PIN_07, GPIO_PORT_A},
									 {GPIO_MODE_OUTPUT_OD, GPIO_PUPD_u32_PULL_DOWN, GPIO_SPEED_VHIGH, GPIO_PIN_08, GPIO_PORT_A},
									 {GPIO_MODE_OUTPUT_OD, GPIO_PUPD_u32_PULL_DOWN, GPIO_SPEED_VHIGH, GPIO_PIN_09, GPIO_PORT_A},
									 {GPIO_MODE_OUTPUT_OD, GPIO_PUPD_u32_PULL_DOWN, GPIO_SPEED_VHIGH, GPIO_PIN_10, GPIO_PORT_A},
									 {GPIO_MODE_OUTPUT_OD, GPIO_PUPD_u32_PULL_DOWN, GPIO_SPEED_VHIGH, GPIO_PIN_11, GPIO_PORT_A},
									 {GPIO_MODE_OUTPUT_OD, GPIO_PUPD_u32_PULL_DOWN, GPIO_SPEED_VHIGH, GPIO_PIN_12, GPIO_PORT_A},
									 {GPIO_MODE_OUTPUT_OD, GPIO_PUPD_u32_PULL_DOWN, GPIO_SPEED_VHIGH, GPIO_PIN_13, GPIO_PORT_A},
									 {GPIO_MODE_OUTPUT_OD, GPIO_PUPD_u32_PULL_DOWN, GPIO_SPEED_VHIGH, GPIO_PIN_14, GPIO_PORT_A},
									 {GPIO_MODE_OUTPUT_OD, GPIO_PUPD_u32_PULL_DOWN, GPIO_SPEED_VHIGH, GPIO_PIN_15, GPIO_PORT_A}
									};

GpioPinCfg_t GPIOB_PINx_CFG[16] = {
									 {GPIO_MODE_OUTPUT_OD, GPIO_PUPD_u32_PULL_DOWN, GPIO_SPEED_VHIGH, GPIO_PIN_00, GPIO_PORT_B},
									 {GPIO_MODE_OUTPUT_OD, GPIO_PUPD_u32_PULL_DOWN, GPIO_SPEED_VHIGH, GPIO_PIN_01, GPIO_PORT_B},
									 {GPIO_MODE_OUTPUT_OD, GPIO_PUPD_u32_PULL_DOWN, GPIO_SPEED_VHIGH, GPIO_PIN_02, GPIO_PORT_B},
									 {GPIO_MODE_OUTPUT_OD, GPIO_PUPD_u32_PULL_DOWN, GPIO_SPEED_VHIGH, GPIO_PIN_03, GPIO_PORT_B},
									 {GPIO_MODE_OUTPUT_OD, GPIO_PUPD_u32_PULL_DOWN, GPIO_SPEED_VHIGH, GPIO_PIN_04, GPIO_PORT_B},
									 {GPIO_MODE_OUTPUT_OD, GPIO_PUPD_u32_PULL_DOWN, GPIO_SPEED_VHIGH, GPIO_PIN_05, GPIO_PORT_B},
									 {GPIO_MODE_OUTPUT_OD, GPIO_PUPD_u32_PULL_DOWN, GPIO_SPEED_VHIGH, GPIO_PIN_06, GPIO_PORT_B},
									 {GPIO_MODE_OUTPUT_OD, GPIO_PUPD_u32_PULL_DOWN, GPIO_SPEED_VHIGH, GPIO_PIN_07, GPIO_PORT_B},
									 {GPIO_MODE_OUTPUT_OD, GPIO_PUPD_u32_PULL_DOWN, GPIO_SPEED_VHIGH, GPIO_PIN_08, GPIO_PORT_B},
									 {GPIO_MODE_OUTPUT_OD, GPIO_PUPD_u32_PULL_DOWN, GPIO_SPEED_VHIGH, GPIO_PIN_09, GPIO_PORT_B},
									 {GPIO_MODE_OUTPUT_OD, GPIO_PUPD_u32_PULL_DOWN, GPIO_SPEED_VHIGH, GPIO_PIN_10, GPIO_PORT_B},
									 {GPIO_MODE_OUTPUT_OD, GPIO_PUPD_u32_PULL_DOWN, GPIO_SPEED_VHIGH, GPIO_PIN_11, GPIO_PORT_B},
									 {GPIO_MODE_OUTPUT_OD, GPIO_PUPD_u32_PULL_DOWN, GPIO_SPEED_VHIGH, GPIO_PIN_12, GPIO_PORT_B},
									 {GPIO_MODE_OUTPUT_OD, GPIO_PUPD_u32_PULL_DOWN, GPIO_SPEED_VHIGH, GPIO_PIN_13, GPIO_PORT_B},
									 {GPIO_MODE_OUTPUT_OD, GPIO_PUPD_u32_PULL_DOWN, GPIO_SPEED_VHIGH, GPIO_PIN_14, GPIO_PORT_B},
									 {GPIO_MODE_OUTPUT_OD, GPIO_PUPD_u32_PULL_DOWN, GPIO_SPEED_VHIGH, GPIO_PIN_15, GPIO_PORT_B}
									};

GpioPinCfg_t GPIOC_PINx_CFG[16] = {
									 {GPIO_MODE_OUTPUT_OD, GPIO_PUPD_u32_PULL_DOWN, GPIO_SPEED_VHIGH, GPIO_PIN_00, GPIO_PORT_C},
									 {GPIO_MODE_OUTPUT_OD, GPIO_PUPD_u32_PULL_DOWN, GPIO_SPEED_VHIGH, GPIO_PIN_01, GPIO_PORT_C},
									 {GPIO_MODE_OUTPUT_OD, GPIO_PUPD_u32_PULL_DOWN, GPIO_SPEED_VHIGH, GPIO_PIN_02, GPIO_PORT_C},
									 {GPIO_MODE_OUTPUT_OD, GPIO_PUPD_u32_PULL_DOWN, GPIO_SPEED_VHIGH, GPIO_PIN_03, GPIO_PORT_C},
									 {GPIO_MODE_OUTPUT_OD, GPIO_PUPD_u32_PULL_DOWN, GPIO_SPEED_VHIGH, GPIO_PIN_04, GPIO_PORT_C},
									 {GPIO_MODE_OUTPUT_OD, GPIO_PUPD_u32_PULL_DOWN, GPIO_SPEED_VHIGH, GPIO_PIN_05, GPIO_PORT_C},
									 {GPIO_MODE_OUTPUT_OD, GPIO_PUPD_u32_PULL_DOWN, GPIO_SPEED_VHIGH, GPIO_PIN_06, GPIO_PORT_C},
									 {GPIO_MODE_OUTPUT_OD, GPIO_PUPD_u32_PULL_DOWN, GPIO_SPEED_VHIGH, GPIO_PIN_07, GPIO_PORT_C},
									 {GPIO_MODE_OUTPUT_OD, GPIO_PUPD_u32_PULL_DOWN, GPIO_SPEED_VHIGH, GPIO_PIN_08, GPIO_PORT_C},
									 {GPIO_MODE_OUTPUT_OD, GPIO_PUPD_u32_PULL_DOWN, GPIO_SPEED_VHIGH, GPIO_PIN_09, GPIO_PORT_C},
									 {GPIO_MODE_OUTPUT_OD, GPIO_PUPD_u32_PULL_DOWN, GPIO_SPEED_VHIGH, GPIO_PIN_10, GPIO_PORT_C},
									 {GPIO_MODE_OUTPUT_OD, GPIO_PUPD_u32_PULL_DOWN, GPIO_SPEED_VHIGH, GPIO_PIN_11, GPIO_PORT_C},
									 {GPIO_MODE_OUTPUT_OD, GPIO_PUPD_u32_PULL_DOWN, GPIO_SPEED_VHIGH, GPIO_PIN_12, GPIO_PORT_C},
									 {GPIO_MODE_OUTPUT_OD, GPIO_PUPD_u32_PULL_DOWN, GPIO_SPEED_VHIGH, GPIO_PIN_13, GPIO_PORT_C},
									 {GPIO_MODE_OUTPUT_OD, GPIO_PUPD_u32_PULL_DOWN, GPIO_SPEED_VHIGH, GPIO_PIN_14, GPIO_PORT_C},
									 {GPIO_MODE_OUTPUT_OD, GPIO_PUPD_u32_PULL_DOWN, GPIO_SPEED_VHIGH, GPIO_PIN_15, GPIO_PORT_C}
									};

GpioPinCfg_t GPIOD_PINx_CFG[16] = {
									 {GPIO_MODE_OUTPUT_OD, GPIO_PUPD_u32_PULL_DOWN, GPIO_SPEED_VHIGH, GPIO_PIN_00, GPIO_PORT_D},
									 {GPIO_MODE_OUTPUT_OD, GPIO_PUPD_u32_PULL_DOWN, GPIO_SPEED_VHIGH, GPIO_PIN_01, GPIO_PORT_D},
									 {GPIO_MODE_OUTPUT_OD, GPIO_PUPD_u32_PULL_DOWN, GPIO_SPEED_VHIGH, GPIO_PIN_02, GPIO_PORT_D},
									 {GPIO_MODE_OUTPUT_OD, GPIO_PUPD_u32_PULL_DOWN, GPIO_SPEED_VHIGH, GPIO_PIN_03, GPIO_PORT_D},
									 {GPIO_MODE_OUTPUT_OD, GPIO_PUPD_u32_PULL_DOWN, GPIO_SPEED_VHIGH, GPIO_PIN_04, GPIO_PORT_D},
									 {GPIO_MODE_OUTPUT_OD, GPIO_PUPD_u32_PULL_DOWN, GPIO_SPEED_VHIGH, GPIO_PIN_05, GPIO_PORT_D},
									 {GPIO_MODE_OUTPUT_OD, GPIO_PUPD_u32_PULL_DOWN, GPIO_SPEED_VHIGH, GPIO_PIN_06, GPIO_PORT_D},
									 {GPIO_MODE_OUTPUT_OD, GPIO_PUPD_u32_PULL_DOWN, GPIO_SPEED_VHIGH, GPIO_PIN_07, GPIO_PORT_D},
									 {GPIO_MODE_OUTPUT_OD, GPIO_PUPD_u32_PULL_DOWN, GPIO_SPEED_VHIGH, GPIO_PIN_08, GPIO_PORT_D},
									 {GPIO_MODE_OUTPUT_OD, GPIO_PUPD_u32_PULL_DOWN, GPIO_SPEED_VHIGH, GPIO_PIN_09, GPIO_PORT_D},
									 {GPIO_MODE_OUTPUT_OD, GPIO_PUPD_u32_PULL_DOWN, GPIO_SPEED_VHIGH, GPIO_PIN_10, GPIO_PORT_D},
									 {GPIO_MODE_OUTPUT_OD, GPIO_PUPD_u32_PULL_DOWN, GPIO_SPEED_VHIGH, GPIO_PIN_11, GPIO_PORT_D},
									 {GPIO_MODE_OUTPUT_OD, GPIO_PUPD_u32_PULL_DOWN, GPIO_SPEED_VHIGH, GPIO_PIN_12, GPIO_PORT_D},
									 {GPIO_MODE_OUTPUT_OD, GPIO_PUPD_u32_PULL_DOWN, GPIO_SPEED_VHIGH, GPIO_PIN_13, GPIO_PORT_D},
									 {GPIO_MODE_OUTPUT_OD, GPIO_PUPD_u32_PULL_DOWN, GPIO_SPEED_VHIGH, GPIO_PIN_14, GPIO_PORT_D},
									 {GPIO_MODE_OUTPUT_OD, GPIO_PUPD_u32_PULL_DOWN, GPIO_SPEED_VHIGH, GPIO_PIN_15, GPIO_PORT_D}
									};

GpioPinCfg_t GPIOE_PINx_CFG[16] = {
									 {GPIO_MODE_OUTPUT_OD, GPIO_PUPD_u32_PULL_DOWN, GPIO_SPEED_VHIGH, GPIO_PIN_00, GPIO_PORT_E},
									 {GPIO_MODE_OUTPUT_OD, GPIO_PUPD_u32_PULL_DOWN, GPIO_SPEED_VHIGH, GPIO_PIN_01, GPIO_PORT_E},
									 {GPIO_MODE_OUTPUT_OD, GPIO_PUPD_u32_PULL_DOWN, GPIO_SPEED_VHIGH, GPIO_PIN_02, GPIO_PORT_E},
									 {GPIO_MODE_OUTPUT_OD, GPIO_PUPD_u32_PULL_DOWN, GPIO_SPEED_VHIGH, GPIO_PIN_03, GPIO_PORT_E},
									 {GPIO_MODE_OUTPUT_OD, GPIO_PUPD_u32_PULL_DOWN, GPIO_SPEED_VHIGH, GPIO_PIN_04, GPIO_PORT_E},
									 {GPIO_MODE_OUTPUT_OD, GPIO_PUPD_u32_PULL_DOWN, GPIO_SPEED_VHIGH, GPIO_PIN_05, GPIO_PORT_E},
									 {GPIO_MODE_OUTPUT_OD, GPIO_PUPD_u32_PULL_DOWN, GPIO_SPEED_VHIGH, GPIO_PIN_06, GPIO_PORT_E},
									 {GPIO_MODE_OUTPUT_OD, GPIO_PUPD_u32_PULL_DOWN, GPIO_SPEED_VHIGH, GPIO_PIN_07, GPIO_PORT_E},
									 {GPIO_MODE_OUTPUT_OD, GPIO_PUPD_u32_PULL_DOWN, GPIO_SPEED_VHIGH, GPIO_PIN_08, GPIO_PORT_E},
									 {GPIO_MODE_OUTPUT_OD, GPIO_PUPD_u32_PULL_DOWN, GPIO_SPEED_VHIGH, GPIO_PIN_09, GPIO_PORT_E},
									 {GPIO_MODE_OUTPUT_OD, GPIO_PUPD_u32_PULL_DOWN, GPIO_SPEED_VHIGH, GPIO_PIN_10, GPIO_PORT_E},
									 {GPIO_MODE_OUTPUT_OD, GPIO_PUPD_u32_PULL_DOWN, GPIO_SPEED_VHIGH, GPIO_PIN_11, GPIO_PORT_E},
									 {GPIO_MODE_OUTPUT_OD, GPIO_PUPD_u32_PULL_DOWN, GPIO_SPEED_VHIGH, GPIO_PIN_12, GPIO_PORT_E},
									 {GPIO_MODE_OUTPUT_OD, GPIO_PUPD_u32_PULL_DOWN, GPIO_SPEED_VHIGH, GPIO_PIN_13, GPIO_PORT_E},
									 {GPIO_MODE_OUTPUT_OD, GPIO_PUPD_u32_PULL_DOWN, GPIO_SPEED_VHIGH, GPIO_PIN_14, GPIO_PORT_E},
									 {GPIO_MODE_OUTPUT_OD, GPIO_PUPD_u32_PULL_DOWN, GPIO_SPEED_VHIGH, GPIO_PIN_15, GPIO_PORT_E}
									};

GpioPinCfg_t GPIOH_PINx_CFG[16] = {
									 {GPIO_MODE_OUTPUT_OD, GPIO_PUPD_u32_PULL_DOWN, GPIO_SPEED_VHIGH, GPIO_PIN_00, GPIO_PORT_H},
									 {GPIO_MODE_OUTPUT_OD, GPIO_PUPD_u32_PULL_DOWN, GPIO_SPEED_VHIGH, GPIO_PIN_01, GPIO_PORT_H},
									 {GPIO_MODE_OUTPUT_OD, GPIO_PUPD_u32_PULL_DOWN, GPIO_SPEED_VHIGH, GPIO_PIN_02, GPIO_PORT_H},
									 {GPIO_MODE_OUTPUT_OD, GPIO_PUPD_u32_PULL_DOWN, GPIO_SPEED_VHIGH, GPIO_PIN_03, GPIO_PORT_H},
									 {GPIO_MODE_OUTPUT_OD, GPIO_PUPD_u32_PULL_DOWN, GPIO_SPEED_VHIGH, GPIO_PIN_04, GPIO_PORT_H},
									 {GPIO_MODE_OUTPUT_OD, GPIO_PUPD_u32_PULL_DOWN, GPIO_SPEED_VHIGH, GPIO_PIN_05, GPIO_PORT_H},
									 {GPIO_MODE_OUTPUT_OD, GPIO_PUPD_u32_PULL_DOWN, GPIO_SPEED_VHIGH, GPIO_PIN_06, GPIO_PORT_H},
									 {GPIO_MODE_OUTPUT_OD, GPIO_PUPD_u32_PULL_DOWN, GPIO_SPEED_VHIGH, GPIO_PIN_07, GPIO_PORT_H},
									 {GPIO_MODE_OUTPUT_OD, GPIO_PUPD_u32_PULL_DOWN, GPIO_SPEED_VHIGH, GPIO_PIN_08, GPIO_PORT_H},
									 {GPIO_MODE_OUTPUT_OD, GPIO_PUPD_u32_PULL_DOWN, GPIO_SPEED_VHIGH, GPIO_PIN_09, GPIO_PORT_H},
									 {GPIO_MODE_OUTPUT_OD, GPIO_PUPD_u32_PULL_DOWN, GPIO_SPEED_VHIGH, GPIO_PIN_10, GPIO_PORT_H},
									 {GPIO_MODE_OUTPUT_OD, GPIO_PUPD_u32_PULL_DOWN, GPIO_SPEED_VHIGH, GPIO_PIN_11, GPIO_PORT_H},
									 {GPIO_MODE_OUTPUT_OD, GPIO_PUPD_u32_PULL_DOWN, GPIO_SPEED_VHIGH, GPIO_PIN_12, GPIO_PORT_H},
									 {GPIO_MODE_OUTPUT_OD, GPIO_PUPD_u32_PULL_DOWN, GPIO_SPEED_VHIGH, GPIO_PIN_13, GPIO_PORT_H},
									 {GPIO_MODE_OUTPUT_OD, GPIO_PUPD_u32_PULL_DOWN, GPIO_SPEED_VHIGH, GPIO_PIN_14, GPIO_PORT_H},
									 {GPIO_MODE_OUTPUT_OD, GPIO_PUPD_u32_PULL_DOWN, GPIO_SPEED_VHIGH, GPIO_PIN_15, GPIO_PORT_H}
									};


#endif /* GPIO_GPIO_INCLUDES_GPIO_CFG_H_ */
