#ifndef PORT_CFG_H_
#define PORT_CFG_H_




/*PORTA MODE*/
#define PIN_ID0_MODE   PIN_OUT_HIGH 
#define PIN_ID1_MODE   PIN_OUT_LOW    
#define PIN_ID2_MODE   PIN_IN_FLOAT 
#define PIN_ID3_MODE   PIN_IN_PULLUP    
#define PIN_ID4_MODE   PIN_IN_FLOAT    
#define PIN_ID5_MODE   PIN_IN_FLOAT    
#define PIN_ID6_MODE   PIN_IN_FLOAT   
#define PIN_ID7_MODE   PIN_IN_FLOAT   
#define PIN_ID8_MODE   PIN_IN_FLOAT   
/*PORT MODE*/
#define PIN_ID8_MODE    PIN_IN_FLOAT   
#define PIN_ID9_MODE    PIN_IN_FLOAT 
#define PIN_ID10_MODE   PIN_IN_FLOAT
#define PIN_ID11_MODE   PIN_IN_FLOAT
#define PIN_ID12_MODE   PIN_IN_FLOAT
#define PIN_ID13_MODE   PIN_IN_FLOAT
#define PIN_ID14_MODE   PIN_IN_FLOAT
#define PIN_ID15_MODE   PIN_IN_FLOAT
/*PORTC MODE*/
#define PIN_ID17_MODE   PIN_IN_FLOAT      
#define PIN_ID16_MODE   PIN_IN_FLOAT  
#define PIN_ID18_MODE   PIN_IN_FLOAT  
#define PIN_ID19_MODE   PIN_IN_FLOAT  
#define PIN_ID20_MODE   PIN_IN_FLOAT  
#define PIN_ID21_MODE   PIN_IN_FLOAT  
#define PIN_ID22_MODE   PIN_IN_FLOAT  
#define PIN_ID23_MODE   PIN_IN_FLOAT  
/*PORTB MODE*/
#define PIN_ID24_MODE   PIN_IN_FLOAT   
#define PIN_ID25_MODE   PIN_IN_FLOAT   
#define PIN_ID26_MODE   PIN_IN_FLOAT   
#define PIN_ID27_MODE   PIN_IN_FLOAT   
#define PIN_ID28_MODE   PIN_IN_FLOAT   
#define PIN_ID29_MODE   PIN_IN_FLOAT   
#define PIN_ID30_MODE   PIN_IN_FLOAT   
#define PIN_ID31_MODE   PIN_IN_FLOAT    

#endif