#ifndef KEYPAD_CFG_H
#define	KEYPAD_CFG_H

#define ROW0PIN			PORT_u8PORTCPIN5
#define ROW1PIN			PORT_u8PORTCPIN4
#define ROW2PIN			PORT_u8PORTCPIN3
#define ROW3PIN			PORT_u8PORTCPIN2

#define COLOUMN0PIN		PORT_u8PORTDPIN7
#define COLOUMN1PIN		PORT_u8PORTDPIN6
#define COLOUMN2PIN		PORT_u8PORTDPIN5
#define COLOUMN3PIN		PORT_u8PORTDPIN3



#endif