/*
 * PORT_cfg.h
 *
 * Created: 10/20/2023 11:59:12 AM
 *  Author: FADY
 */ 


#ifndef PORT_CFG_H_
#define PORT_CFG_H_

/* Intial Values for All Pins */
/* Options : PORT_OUTPUT_LOW
			 PORT_OUTPUT_HIGH
			 PORT_INPUT_FLOATING
			 PORT_INPUT_PULLUP   */

/* PORTA */	

#define PORT_PA0_INTIAL_STATE               PORT_OUTPUT_LOW       
#define PORT_PA1_INTIAL_STATE               PORT_OUTPUT_LOW 
#define PORT_PA2_INTIAL_STATE               PORT_OUTPUT_LOW 
#define PORT_PA3_INTIAL_STATE               PORT_OUTPUT_LOW 
#define PORT_PA4_INTIAL_STATE               PORT_OUTPUT_LOW 
#define PORT_PA5_INTIAL_STATE               PORT_OUTPUT_LOW
#define PORT_PA6_INTIAL_STATE               PORT_INPUT_FLOATING 
#define PORT_PA7_INTIAL_STATE               PORT_INPUT_FLOATING
/* PORTB*/	

#define PORT_PB0_INTIAL_STATE               PORT_OUTPUT_LOW 
#define PORT_PB1_INTIAL_STATE               PORT_OUTPUT_LOW
#define PORT_PB2_INTIAL_STATE               PORT_OUTPUT_LOW 
#define PORT_PB3_INTIAL_STATE               PORT_OUTPUT_LOW
#define PORT_PB4_INTIAL_STATE               PORT_INPUT_PULLUP
#define PORT_PB5_INTIAL_STATE               PORT_INPUT_PULLUP
#define PORT_PB6_INTIAL_STATE               PORT_INPUT_PULLUP
#define PORT_PB7_INTIAL_STATE               PORT_INPUT_PULLUP
/*
#define PORT_PB4_INTIAL_STATE               PORT_INPUT_PULLUP 
#define PORT_PB5_INTIAL_STATE               PORT_INPUT_PULLUP
#define PORT_PB6_INTIAL_STATE               PORT_OUTPUT_LOW 
#define PORT_PB7_INTIAL_STATE               PORT_INPUT_PULLUP*/

/*
#define PORT_PB4_INTIAL_STATE               PORT_OUTPUT_LOW
#define PORT_PB5_INTIAL_STATE               PORT_OUTPUT_LOW
#define PORT_PB6_INTIAL_STATE               PORT_INPUT_PULLUP
#define PORT_PB7_INTIAL_STATE               PORT_OUTPUT_LOW
*/
/* PORTC */	

#define PORT_PC0_INTIAL_STATE               PORT_OUTPUT_LOW 
#define PORT_PC1_INTIAL_STATE               PORT_OUTPUT_LOW
#define PORT_PC2_INTIAL_STATE               PORT_OUTPUT_LOW  
#define PORT_PC3_INTIAL_STATE               PORT_OUTPUT_LOW
#define PORT_PC4_INTIAL_STATE               PORT_OUTPUT_LOW 
#define PORT_PC5_INTIAL_STATE               PORT_OUTPUT_LOW
#define PORT_PC6_INTIAL_STATE               PORT_OUTPUT_LOW 
#define PORT_PC7_INTIAL_STATE               PORT_OUTPUT_LOW

/* PORTD */	

#define PORT_PD0_INTIAL_STATE               PORT_OUTPUT_HIGH 
#define PORT_PD1_INTIAL_STATE               PORT_OUTPUT_HIGH
#define PORT_PD2_INTIAL_STATE               PORT_INPUT_FLOATING  
#define PORT_PD3_INTIAL_STATE               PORT_OUTPUT_HIGH
#define PORT_PD4_INTIAL_STATE               PORT_OUTPUT_HIGH 
#define PORT_PD5_INTIAL_STATE               PORT_OUTPUT_HIGH
#define PORT_PD6_INTIAL_STATE               PORT_OUTPUT_HIGH 
#define PORT_PD7_INTIAL_STATE               PORT_OUTPUT_HIGH



#endif 