/*
 * PORT_cfg.h
 *
 *  Created on: Oct 20, 2023
 *      Author: Ismail
 */

#ifndef MCAL_PORT_PORT_CFG_H_
#define MCAL_PORT_PORT_CFG_H_
 /*
  	 PORT_OPTIONS:
  	1-PORT_u8OUTPUT_HIGH
	2-PORT_u8OUTPUT_LOW
	3-PORT_u8INPUT_FLOATING   FLOATING IS THE INTIAL STATE OF THE PIN
	4-PORT_u8INPUT_PULLUP
	*/
//those values suit our LCD AND ADC  task
	//PORTA
#define PORT_u8MODE_PIN0            PORT_u8INPUT_FLOATING
#define PORT_u8MODE_PIN1            PORT_u8OUTPUT_HIGH
#define PORT_u8MODE_PIN2            PORT_u8OUTPUT_HIGH
#define PORT_u8MODE_PIN3            PORT_u8OUTPUT_HIGH
#define PORT_u8MODE_PIN4            PORT_u8INPUT_FLOATING
#define PORT_u8MODE_PIN5            PORT_u8INPUT_FLOATING
#define PORT_u8MODE_PIN6            PORT_u8INPUT_FLOATING
#define PORT_u8MODE_PIN7            PORT_u8INPUT_FLOATING
	//PORTB
#define PORT_u8MODE_PIN8            PORT_u8OUTPUT_HIGH
#define PORT_u8MODE_PIN9            PORT_u8OUTPUT_HIGH
#define PORT_u8MODE_PIN10           PORT_u8OUTPUT_HIGH
#define PORT_u8MODE_PIN11           PORT_u8OUTPUT_HIGH
#define PORT_u8MODE_PIN12            PORT_u8INPUT_FLOATING
#define PORT_u8MODE_PIN13            PORT_u8INPUT_FLOATING
#define PORT_u8MODE_PIN14            PORT_u8INPUT_FLOATING
#define PORT_u8MODE_PIN15            PORT_u8INPUT_FLOATING
	//PORTC
#define PORT_u8MODE_PIN16            PORT_u8INPUT_FLOATING
#define PORT_u8MODE_PIN17            PORT_u8INPUT_FLOATING
#define PORT_u8MODE_PIN18            PORT_u8INPUT_FLOATING
#define PORT_u8MODE_PIN19            PORT_u8INPUT_FLOATING
#define PORT_u8MODE_PIN20            PORT_u8INPUT_FLOATING
#define PORT_u8MODE_PIN21            PORT_u8INPUT_FLOATING
#define PORT_u8MODE_PIN22            PORT_u8INPUT_FLOATING
#define PORT_u8MODE_PIN23            PORT_u8INPUT_FLOATING
	//PORTD
#define PORT_u8MODE_PIN24            PORT_u8INPUT_FLOATING
#define PORT_u8MODE_PIN25            PORT_u8INPUT_FLOATING
#define PORT_u8MODE_PIN26            PORT_u8OUTPUT_HIGH
#define PORT_u8MODE_PIN27            PORT_u8INPUT_FLOATING
#define PORT_u8MODE_PIN28            PORT_u8INPUT_FLOATING
#define PORT_u8MODE_PIN29            PORT_u8INPUT_FLOATING
#define PORT_u8MODE_PIN30            PORT_u8INPUT_FLOATING
#define PORT_u8MODE_PIN31            PORT_u8INPUT_FLOATING

#endif /* MCAL_PORT_PORT_CFG_H_ */
