#ifndef ADC_CONFIG_H_
#define ADC_CONFIG_H_

#define VOLTAGE_REFERENCE_SELECTION AVCC_CAPACITOR_AT_AREF

#define ADC_CONVERSION_FORM LEFT_ADJUSTED

#define ANALOG_CHANNEL_AND_GAIN_SELECTION_REFERENCE     SEI_ADC0

#define ADC_ENABLE ENABLED

#define ADC_AUTO_TRIGGER_ENABLE DISABLED

#define ADC_INTERRUPT_ENABLE ENABLED

#define ADC_PRESCALER_SET_BITS  DIVISION_FACTOR_16

#define AUTO_TRIGGER_SOURCE FREE_RUNNING_MODE

#endif /* ADC_CONFIG_H_ */
